//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddToursTable
    {
        public int Id { get; set; }
        public string AddTour { get; set; }
        public string AddHotel { get; set; }
        public string AddHotelCost { get; set; }
        public string AddLocation { get; set; }
        public string AddDestination { get; set; }
        public string Selecttransport { get; set; }
        public string AddTransportCost { get; set; }
    }
}
