//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Datacontext2 : DbContext
    {
        public Datacontext2()
            : base("name=Datacontext2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminTable> AdminTables { get; set; }
        public DbSet<custregTable> custregTables { get; set; }
        public DbSet<AddToursTable> AddToursTables { get; set; }
    }
    //new

    
}
